### ISSUE TITLE
smbclient: Broken Pipe error when python kernel sits too long

### ISSUE THREAD

**Issue by kevmk04** [jborean93/smbprotocol#31]
Firstly, thanks for writing this module. I've been able to get it to connect to our windows shares to open and find files from a JupyterLab environment.  

The issue I've having is that if I let my python kernel sit for a bit (>10 minutes or so), I will get a [Errno 32] Broken Pipe error when I try to use `smbclient.open_file` or `smbclient.listdir`.  I tried to use the `smbclient.reset_connection_cache()` function to fix it but also got the broken pipe error.  I was able to resolve this by restarting the python kernel.  I'm guessing that my connection to the server is being disconnected, but I would expect that there could be a way to re-connect without restarting the kernel or throwing an error. Thoughts?

**System Information:** 
Environment: JupyterHub (TLJH) /JupyterLab V1.1.3 running on an Ubuntu 18 server
Python: 3.6

Here are details of the error from the listdir command:

`---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
<ipython-input-14-aeb8318e4032> in <module>
----> 1 smbclient.listdir(r"\\servername\removed")

/opt/tljh/user/lib/python3.6/site-packages/smbclient/_os.py in listdir(path, search_pattern, **kwargs)
    218     :return: A list containing the names of the entries in the directory.
    219     """
--> 220     with SMBDirectoryIO(path, mode='r', share_access='r', **kwargs) as dir_fd:
    221         try:
    222             raw_filenames = dir_fd.query_directory(search_pattern, FileInformationClass.FILE_NAMES_INFORMATION)

/opt/tljh/user/lib/python3.6/site-packages/smbclient/_io.py in __enter__(self)
    292 
    293     def __enter__(self):
--> 294         self.open()
    295         return self
    296 

/opt/tljh/user/lib/python3.6/site-packages/smbclient/_io.py in open(self, transaction)
    338                 create_disposition,
    339                 self._create_options,
--> 340                 send=(transaction is None),
    341             )
    342         except SMBResponseException as exc:

/opt/tljh/user/lib/python3.6/site-packages/smbprotocol/open.py in create(self, impersonation_level, desired_access, file_attributes, share_access, create_disposition, create_options, create_contexts, oplock_level, send)
   1208         request = self.connection.send(create,
   1209                                        self.tree_connect.session.session_id,
-> 1210                                        self.tree_connect.tree_connect_id)
   1211         return self._create_response(request)
   1212 

/opt/tljh/user/lib/python3.6/site-packages/smbprotocol/connection.py in send(self, message, sid, tid, credit_request, message_id, async_id)
    964         """
    965         return self._send([message], session_id=sid, tree_id=tid, message_id=message_id, credit_request=credit_request,
--> 966                           async_id=async_id)[0]
    967 
    968     def send_compound(self, messages, sid, tid, related=False):

/opt/tljh/user/lib/python3.6/site-packages/smbprotocol/connection.py in wrapped(self, *args, **kwargs)
    761     def wrapped(self, *args, **kwargs):
    762         self._check_worker_running()
--> 763         return func(self, *args, **kwargs)
    764     return wrapped
    765 

/opt/tljh/user/lib/python3.6/site-packages/smbprotocol/connection.py in _send(self, messages, session_id, tree_id, message_id, credit_request, related, async_id)
   1242             send_data = self._encrypt(send_data, session)
   1243 
-> 1244         self.transport.send(send_data)
   1245         return requests
   1246 

/opt/tljh/user/lib/python3.6/site-packages/smbprotocol/transport.py in wrapped(self, *args, **kwargs)
     65             self._connected = True
     66 
---> 67         func(self, *args, **kwargs)
     68 
     69     return wrapped

/opt/tljh/user/lib/python3.6/site-packages/smbprotocol/transport.py in send(self, header)
    106         data = tcp_packet.pack()
    107         while data:
--> 108             sent = self._sock.send(data)
    109             data = data[sent:]
    110 

BrokenPipeError: [Errno 32] Broken pipe`

**Comment by jborean93** [comment]
> The issue I've having is that if I let my python kernel sit for a bit 

By this do you mean that you have a Python interpreter running that has already opened a connection/session to your Windows host. You wait a few more minutes of it doing nothing and try and connect again and it fails with that message?

**Comment by kevmk04** [comment]
Yes, I use the smbclient functions to connect to my server, do something, and then let the python environment sit for a bit. If I try to use one of the functions after the delay and without restarting python, I get that error.

**Comment by jborean93** [comment]
Thanks for the confirmation, I will have to play around with this a bit and find a solution. I can't guarantee I will get to it straight away but will try my best.

**Comment by DArtagan** [comment]
My team was encountering this exact same error too.  We've poked at it for a few days.  We also found that once the error has started, anything that opens a connection to the host will crash, including `smbclient.reset_connection_cache()`.

A work around we found: before each bundle of SMB operations, use `smbclient.register_session()`.  After a bundle of operations, close any open files (if necessary) and then run `smbclient.reset_connection_cache()`.

**Comment by DArtagan** [comment]
Follow up: sorry, that fix seemed to hold for a few days, but eventually broke down - not sure why.

**Comment by pietromingo** [comment]
Hello everyone,
I think I have the same problem, I have a celery task that runs every minute, if it finds things to do it opens a connection and saves a file, it finds a stuck after a while with `BrokenPipeError` and I have to restart celery.
When I have a `BrokenPipeError` I do `reset_connection_cache()` but it doesn't seem to work

```
Traceback (most recent call last):
  File "/home/inta/inta/djangocustom/tasks.py", line 77, in export_stack_external
    with open_file("{0}\{1}".format(dir, filename), mode="w", username=STACK_USERNAME, password=STACK_PASSWORD) as fd:
  File "/home/inta/env/lib/python3.5/site-packages/smbclient/_os.py", line 358, in open_file
    raw_fd.open()
  File "/home/inta/env/lib/python3.5/site-packages/smbclient/_io.py", line 340, in open
    send=(transaction is None),
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/open.py", line 1210, in create
    self.tree_connect.tree_connect_id)
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/connection.py", line 966, in send
    async_id=async_id)[0]
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/connection.py", line 763, in wrapped
    return func(self, *args, **kwargs)
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/connection.py", line 1244, in _send
    self.transport.send(send_data)
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/transport.py", line 67, in wrapped
    func(self, *args, **kwargs)
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/transport.py", line 108, in send
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inta/env/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/inta/env/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/inta/inta/django/custom/tasks.py", line 121, in export_stack_external
    reset_connection_cache()
  File "/home/inta/env/lib/python3.5/site-packages/smbclient/_pool.py", line 135, in reset_connection_cache
    connection.disconnect()
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/connection.py", line 947, in disconnect
    session.disconnect(True)
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/session.py", line 414, in disconnect
    tree.disconnect()
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/tree.py", line 286, in disconnect
    tid=self.tree_connect_id)
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/connection.py", line 966, in send
    async_id=async_id)[0]
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/connection.py", line 763, in wrapped
    return func(self, *args, **kwargs)
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/connection.py", line 1244, in _send
    self.transport.send(send_data)
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/transport.py", line 67, in wrapped
    func(self, *args, **kwargs)
  File "/home/inta/env/lib/python3.5/site-packages/smbprotocol/transport.py", line 108, in send
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

```

**Comment by ethankleinman** [comment]
A workaround that's been working for me so far is to run `smbclient.register_session` before running any other method (like `with smbclient.open_file():`), then run `smbclient.delete_session` right afterwords.

**Comment by kevmk04** [comment]
@ethankleinman Good suggestion.  I can confirm that `smbclient.delete_session` does seem to prevent the pipe error if I call it right after any of the other methods.  I found that `smbclient.register_session` doesn't appear to be necessary as it is called by those other methods (open_file, etc).

**Comment by jborean93** [comment]
Sorry for the delay on looking into this one. I believe I've fixed the main part of this bug with https://github.com/jborean93/smbprotocol/pull/50. I've tested it in a few different scenarios and I no longer can reproduce the Broken pipe error from before. There may still be problems that I haven't encountered in the future but that should be tracked in a different issue. For now I consider this bug fixed and will be in the 1.2.0 release of smbprotocol.

**Comment by emmanoedorh** [comment]
Hi
I'm using smbprotocol 1.15.0 and still getting this broken pipe error while trying to open a 1gb zip file from a windows server

Traceback (most recent call last):
  File "/usr/src/app/lib/my_os.py", line 46, in get_smb_session
    yield smb_session
  File "/usr/src/app/lib/my_os.py", line 356, in my_os_unzip
    with smbclient.open_file(src_zip_file, "rb") as zip_archive_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/smbclient/_os.py", line 533, in open_file
    raw_fd.open()
  File "/usr/local/lib/python3.12/site-packages/smbclient/_io.py", line 463, in open
    transaction.commit()
  File "/usr/local/lib/python3.12/site-packages/smbclient/_io.py", line 284, in commit
    requests = self.raw.fd.connection.send_compound(send_msgs, sid, tid, related=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/smbprotocol/connection.py", line 998, in send_compound
    return self._send(messages, session_id=sid, tree_id=tid, related=related)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
